---
- name: Check and update Apache if version is below 2.4
  hosts: all
  become: yes
  tasks:

    - name: Check current Apache version
      command: httpd -v
      register: apache_version
      ignore_errors: yes  # 오류 발생 시에도 다음 태스크로 진행

    - name: Display current Apache version
      debug:
        msg: "Current Apache version: {{ apache_version.stdout | default('Not installed') }}"

    - name: Check if Apache is installed
      fail:
        msg: "Apache is not installed. Please install Apache first."
      when: apache_version.rc != 0

    - name: Extract major and minor version numbers
      set_fact:
        version_string: "{{ apache_version.stdout.split()[2] }}"
        major_version: "{{ version_string.split('.')[0] | int }}"
        minor_version: "{{ version_string.split('.')[1] | int }}"

    - name: Check if Apache version is below 2.4
      debug:
        msg: "Apache version is below 2.4. Major: {{ major_version }}, Minor: {{ minor_version }}"
      when: (major_version < 2) or (major_version == 2 and minor_version < 4)

    - name: Update Apache to the latest version
      yum:
        name: httpd
        state: latest
      when: (major_version < 2) or (major_version == 2 and minor_version < 4)

    - name: Ensure Apache is running
      service:
        name: httpd
        state: started
        enabled: yes
