# header
- set_fact:
    diag: "{{ {'항목': '디렉터리 리스팅 제거', 'id': 5, '조치방안': 'Options Indexes FollowSymLinks 주석처리'} }}"

# body

# 1. Get PermitRootLogin setting from sshd_config
- name: Get PermitRootLogin setting from sshd_config
  ansible.builtin.shell: grep -E '^[[:space:]]*PermitRootLogin' /etc/ssh/sshd_config
  register: permit_root_login
  ignore_errors: yes

# 2. Evaluate PermitRootLogin setting
- set_fact:
    weak: >
      {% if permit_root_login.rc != 0 %}
        true
      {% elif 'PermitRootLogin no' in permit_root_login.stdout %}
        false
      {% elif 'PermitRootLogin prohibit-password' in permit_root_login.stdout %}
        true
      {% else %}
        true
      {% endif %}

- debug:
    msg: "Weak variable value1: {{ weak }}"

# 3. Check Apache httpd.conf for "Indexes" option
- name: Ensure /etc/httpd/conf/httpd.conf exists
  become: true
  stat:
    path: /etc/httpd/conf/httpd.conf
  register: httpd_conf

- name: Search for "Indexes" option in httpd.conf
  shell: grep -E "^\s*Options.*Indexes" /etc/httpd/conf/httpd.conf
  register: indexes_option
  when: httpd_conf.stat.exists
  failed_when: false
  changed_when: false

- name: Output "Y" if Indexes option is found
  debug:
    msg: "Indexes 옵션이 있음 -> 디렉터리 검색 가능, 취약!!!"
  when: indexes_option.stdout != ""

- name: Output "N" if Indexes option is not found
  debug:
    msg: "Indexes 옵션이 없음 -> 디렉터리 검색 불가, 양호!!!"
  when: indexes_option.stdout == ""

# 4. Combine both checks into the final result
# Remove comments and check the value of weak
- set_fact:
    weak_cleaned: "{{ (weak | string | split('#')) | first | trim }}"

- debug:
    msg: "Weak cleaned value: '{{ weak_cleaned }}'"

# If weak_cleaned contains 'true' or 'false', set weak to boolean
- set_fact:
    weak: "{{ weak_cleaned | lower == 'true' }}"

# Show the final weak variable value
- debug:
    var: weak

# 5. Final result
- block:
    - debug:
        msg: "취약"
    - set_fact:
        result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': True}] }}"
  when: weak or indexes_option.stdout != ""

- block:
    - debug:
        msg: "양호"
    - set_fact:
        result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': False}] }}"
  when: not weak and indexes_option.stdout == ""
