---
- name: Apache 매뉴얼 파일 및 디렉터리 존재 여부 취약점 진단
  hosts: intranetweb
  tasks:
    - name: manual 파일 존재 여부 확인
      stat:
        path: /etc/httpd/conf/manual
      register: manual_file

    - debug:
        msg: >
          {% if manual_file.stat.exists %}
            "취약"
          {% else %}
            "양호"
          {% endif %}
          
    - name: 매뉴얼 디렉터리 존재 여부 출력
      shell: cat /etc/httpd/conf/httpd.conf | grep manual
      register: grep_result
      ignore_errors: true  # grep 결과가 없을 경우 오류를 무시
    - debug:
        msg: >
          {% if grep_result.stdout %}
            "취약"
          {% else %}
            "양호"
          {% endif %}
