- set_fact:
    diag: "{{ {'항목': '/etc/(x)inetd.conf 파일 소유자 및 권한 설정', 'id': 11, '조치방안': '파일 소유자 root로 변경 및 권한 변경'} }}"

- name: Check for /etc/xinetd.conf
  ansible.builtin.command: "ls -l /etc/xinetd.conf"
  register: xinetd_conf
  ignore_errors: yes
  failed_when: false

- name: Check for /etc/inetd.conf
  ansible.builtin.command: "ls -l /etc/inetd.conf"
  register: inetd_conf
  ignore_errors: yes
  failed_when: false

- name: Determine if both files are missing
  set_fact:
    files_missing: "{{ xinetd_conf.rc != 0 and inetd_conf.rc != 0 }}"

- name: Display result for file checks
  debug:
    msg: >
      {%
        if files_missing
        %}
        No /etc/xinetd.conf and /etc/inetd.conf files found. System is secure.
        {% else %}
        At least one of the files exists. Requires further investigation.
        {% endif %}

- block:
    - debug:
        msg: "취약"
    - set_fact:
        result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': True, '조치방안': diag.조치방안}] }}"
  when: weak

- block:
    - debug:
        msg: "양호"
    - set_fact:
        result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': False, '조치방안': diag.조치방안}] }}"
  when: not weak
