- set_fact:
    diag: "{{ {'항목': '/etc/shadow 파일 소유자 및 권한 설', 'id': 9} }}"  # 여기서 항목과 ID 설정

- name: Check password complexity setting
  ansible.builtin.command: "grep pam_pwquality.so /etc/pam.d/system-auth"
  register: complexity_output

- name: Validate if password complexity is enforced
  set_fact:
    complexity_enabled: "{{ 'retry=' in complexity_output.stdout }}"

- name: Display password complexity setting
  debug:
    msg: "Password complexity setting: {{ complexity_output.stdout }}"

- name: Check if password complexity is enforced
  debug:
    msg: >
      {{
        'Password complexity is enforced.'
        if complexity_enabled
        else 'Password complexity is not enforced.'
      }}

# result 업데이트 블록
- block:
    - debug:
        msg: "취약"
    - set_fact:
        result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': True}] }}"
  when: not complexity_enabled

- block:
    - debug:
        msg: "양호"
    - set_fact:
        result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': False}] }}"
  when: complexity_enabled
