# header
- set_fact:
    diag: "{{ {'항목': 'finger 서비스 비활성화 확인', 'id': 20} }}"

# body
# Step 1: Check if /etc/xinetd.d/finger exists and check the 'disable' status
- name: Check if /etc/xinetd.d/finger exists
  ansible.builtin.stat:
    path: /etc/xinetd.d/finger
  register: finger_xinetd_file

- name: Check disable status in /etc/xinetd.d/finger
  ansible.builtin.shell: grep 'disable' /etc/xinetd.d/finger
  register: disable_finger_xinetd
  when: finger_xinetd_file.stat.exists
  ignore_errors: yes

# Step 1.1: Debug the disable value from /etc/xinetd.d/finger
- name: Debug disable_finger_xinetd stdout
  debug:
    msg: "disable value from /etc/xinetd.d/finger: {{ disable_finger_xinetd.stdout }}"

# Step 2: Check if /etc/inetd.conf contains any finger service entry
- name: Check if /etc/inetd.conf exists
  ansible.builtin.stat:
    path: /etc/inetd.conf
  register: inetd_conf_file

- name: Check for finger service in /etc/inetd.conf
  ansible.builtin.shell: grep '^finger' /etc/inetd.conf
  register: inetd_conf_finger
  when: inetd_conf_file.stat.exists
  ignore_errors: yes

# Step 3: Determine if finger service is disabled in /etc/xinetd.d/finger (after removing spaces)
- name: Determine if finger service is disabled in /etc/xinetd.d/finger
  set_fact:
    finger_disabled_xinetd: "{{ disable_finger_xinetd.stdout | regex_replace('\\s+', '') is search('disable=yes') }}"
  when: finger_xinetd_file.stat.exists

# Step 3.1: Debug the evaluated finger_disabled_xinetd value
- name: Debug finger_disabled_xinetd value
  debug:
    msg: "Is finger service disabled? {{ finger_disabled_xinetd }}"
  when: finger_xinetd_file.stat.exists

# Step 4: Determine if finger service is commented out in /etc/inetd.conf
- name: Determine if finger service is commented out in /etc/inetd.conf
  set_fact:
    finger_commented_in_inetd: "{{ inetd_conf_finger.stdout is search('^#') }}"
  when: inetd_conf_file.stat.exists

# Step 5: Define weak state based on conditions
- name: Check if system is vulnerable
  set_fact:
    weak: "{{ 
      (finger_xinetd_file.stat.exists and not finger_disabled_xinetd) or 
      (inetd_conf_file.stat.exists and not finger_commented_in_inetd)
    }}"
  when: finger_xinetd_file.stat.exists or inetd_conf_file.stat.exists

# Step 6: If both files are absent or finger service is disabled, consider the system secure
- name: Mark system as secure if finger service is disabled or both files are absent
  set_fact:
    weak: false
  when: 
    - (finger_xinetd_file.stat.exists and finger_disabled_xinetd) or
      (inetd_conf_file.stat.exists and finger_commented_in_inetd) or
      (not finger_xinetd_file.stat.exists and not inetd_conf_file.stat.exists)

# Step 7: Display the vulnerability status
- name: Display the vulnerability status
  debug:
    msg: >
      Vulnerable? {{ weak | ternary('True', 'False') }}.
      /etc/xinetd.d/finger exists? {{ finger_xinetd_file.stat.exists }}.
      /etc/inetd.conf exists? {{ inetd_conf_file.stat.exists }}.

# result
- block:
    - debug:
        msg: "취약"
    - set_fact:
        result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': True}] }}"
  when: weak

- block:
    - debug:
        msg: "양호"
    - set_fact:
        result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': False}] }}"
  when: not weak
