- set_fact:
    diag: "{{ {'항목': '일반 사용자의 Sendmail 실행 방지', 'id': 32, '조치방안': ''} }}"  # 항목명과 ID 설정

- name: Check for PrivacyOptions in Sendmail configuration
  ansible.builtin.shell: "cat /etc/mail/sendmail.cf | grep PrivacyOptions"
  register: sendmail_privacy
  ignore_errors: yes

- name: Display Sendmail PrivacyOptions status
  debug:
    msg: "{{ sendmail_privacy.stdout if sendmail_privacy.stdout else 'Sendmail is not configured or PrivacyOptions not set' }}"

- name: Check if 'restrictqrun' is in Sendmail PrivacyOptions
  debug:
    msg: "'restrictqrun' not in sendmail_privacy.stdout: {{ 'restrictqrun' not in sendmail_privacy.stdout }}"


- name: Display Sendmail PrivacyOptions status
  debug:
    msg: "{{ sendmail_privacy.stdout if sendmail_privacy.stdout else 'Sendmail is not configured or PrivacyOptions not set' }}"

- name: Check if Postfix binary exists
  ansible.builtin.shell: "ls -l /usr/sbin/postfix"
  register: postfix_check
  ignore_errors: yes

- name: Display Postfix check return code
  debug:
    msg: "Postfix check return code: {{ postfix_check.rc }}"  

- name: Display Postfix binary status
  debug:
    msg: "{{ 'Postfix is installed' if postfix_check.stdout else 'Postfix is not installed' }}"

- name: Check if Postfix group exists
  ansible.builtin.shell: "getent group postfix"
  register: postfix_group
  ignore_errors: yes

- name: Display Postfix group status
  debug:
    msg: "{{ postfix_group.stdout if postfix_group.stdout else 'Postfix group does not exist or has no members' }}"

- name: Determine if Sendmail and Postfix configuration is weak
  set_fact:
    weak: >-
      {{ 
        ('restrictqrun' not in sendmail_privacy.stdout) 
        or (postfix_check.rc == 0)
      }}

- block:
    - debug:
        msg: "취약"
    - set_fact:
        result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': True, '조치방안': diag.조치방안}] }}"
  when: weak

- block:
    - debug:
        msg: "양호"
    - set_fact:
        result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': False, '조치방안': diag.조치방안}] }}"
  when: not weak

