---
- name: Check if "." is in PATH (only as a standalone entry, not part of a directory)
  hosts: intranetweb
  gather_facts: false
  tasks:
    # Step 1: Get the PATH environment variable
    - name: Get the PATH environment variable
      ansible.builtin.shell: bash -l -c 'echo $PATH'
      register: path_value
      ignore_errors: yes

    # Step 2: Debug PATH value from stdout
    - name: Debug PATH value from stdout
      debug:
        msg: "PATH stdout: {{ path_value.stdout }}"

    # Step 3: Check if "." is at the beginning of PATH as a standalone entry
    - name: Check if "." is at the beginning of PATH
      set_fact:
        is_weak_start: "{{ path_value.stdout | regex_search('(^|:)(\\.)(:|$)') is not none and path_value.stdout | regex_search('/\\.local') is none }}"

    # Step 4: Check if "." is in the middle of PATH as a standalone entry
    - name: Check if "." is in the middle of PATH as a standalone entry
      set_fact:
        is_weak_middle: "{{ path_value.stdout | regex_search(':\\.(?=:|$)') is not none and path_value.stdout | regex_search('/\\.local') is none }}"

    # Step 5: Check if "." is at the end of PATH as a standalone entry
    - name: Check if "." is at the end of PATH as a standalone entry
      set_fact:
        is_weak_end: "{{ path_value.stdout | regex_search(':\\.$') is not none }}"

    # Step 6: Determine if the system is vulnerable (ignore "." when it's part of a valid directory)
    - name: Determine if the system is vulnerable
      set_fact:
        weak: "{{ is_weak_start or is_weak_middle or is_weak_end }}"

    # Step 7: Display the PATH and vulnerability status
    - name: Display the PATH and vulnerability status
      debug:
        msg: >
          PATH is set to {{ path_value.stdout }}.
          Vulnerable? {{ weak | ternary('True', 'False') }}

    # Step 8: Debug specific cases (if "." is at the beginning, middle, or end)
    - name: Debug if "." is at the beginning of PATH
      debug:
        msg: "'.' is at the beginning of PATH."
      when: is_weak_start

    - name: Debug if "." is in the middle of PATH
      debug:
        msg: "'.' is in the middle of PATH."
      when: is_weak_middle

    - name: Debug if "." is at the end of PATH
      debug:
        msg: "'.' is at the end of PATH."
      when: is_weak_end
