- set_fact:
    diag: "{{ {'항목': '/etc/shadow 파일 소유자 및 권한 설정', 'id': 9, '조치방안': '파일 소유자 root로 변경 및 권한 변경'} }}" 

- name: Run ls -l to get the permissions and owner of /etc/shadow
  ansible.builtin.command: "ls -l /etc/shadow"
  register: ls_output

- name: Extract the owner and permissions from ls output
  set_fact:
    file_owner: "{{ ls_output.stdout.split()[2] }}"
    symbolic_permissions: "{{ ls_output.stdout.split()[0] }}"

- name: Convert symbolic permissions to numeric
  set_fact:
    numeric_permissions: |
      {% set owner_perms = '7' if symbolic_permissions[1:4] == 'rwx' else '6' if symbolic_permissions[1:4] == 'rw-' else '5' if symbolic_permissions[1:4] == 'r-x' else '4' if symbolic_permissions[1:4] == 'r--' else '0' %}
      {% set group_perms = '7' if symbolic_permissions[4:7] == 'rwx' else '6' if symbolic_permissions[4:7] == 'rw-' else '5' if symbolic_permissions[4:7] == 'r-x' else '4' if symbolic_permissions[4:7] == 'r--' else '0' %}
      {% set other_perms = '7' if symbolic_permissions[7:10] == 'rwx' else '6' if symbolic_permissions[7:10] == 'rw-' else '5' if symbolic_permissions[7:10] == 'r-x' else '4' if symbolic_permissions[7:10] == 'r--' else '0' %}
      {{ (owner_perms + group_perms + other_perms) | trim }}

- name: Set weak variable based on file ownership and permissions
  set_fact:
    weak: "{{ not (file_owner == 'root' and numeric_permissions | int <= 400) }}"

- name: Display owner, symbolic and numeric permissions
  debug:
    msg:
      - "File Owner: {{ file_owner }}"
      - "Permissions: {{ symbolic_permissions }}, {{ numeric_permissions }}"

- name: Check if the file is secure
  debug:
    msg: >
      {{
        'Secure: File owner is root and permissions are 400 or less.'
        if file_owner == 'root' and numeric_permissions | int <= 400
        else 'Vulnerable: File owner is not root or permissions exceed 400.'
      }}


- block:
    - debug:
        msg: "취약"
    - set_fact:
        result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': True, '조치방안': diag.조치방안}] }}"
  when: weak

- block:
    - debug:
        msg: "양호"
    - set_fact:
        result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': False, '조치방안': diag.조치방안}] }}"
  when: not weak

