# header
- set_fact:
    diag: "{{ {'항목': 'root 계정 원격 접속 제한', 'id': 1, '조치방안': 'sshd_config 파일에서 PermitRootLogin no 로 설정'} }}"

# body

# Get PermitRootLogin setting from sshd_config
- name: Get PermitRootLogin setting from sshd_config
  ansible.builtin.shell: grep -E '^[[:space:]]*PermitRootLogin' /etc/ssh/sshd_config
  register: permit_root_login
  ignore_errors: yes

# weak?
- set_fact:
    weak: >
      {% if permit_root_login.rc != 0 %}
        true
      {% elif 'PermitRootLogin no' in permit_root_login.stdout %}
        false
      {% elif 'PermitRootLogin prohibit-password' in permit_root_login.stdout %}
        true
      {% else %}
        true
      {% endif %}
- debug:
    msg: "Weak variable value1: {{ weak }}"

# Remove comments and check the value of weak
- set_fact:
    weak_cleaned: "{{ weak.split('#')[0].strip() }}"

# Debug the cleaned weak value
- debug:
    msg: "Weak cleaned value: '{{ weak_cleaned }}'"

# If weak_cleaned contains 'true' or 'false', set weak to boolean
- set_fact:
    weak: "{{ weak_cleaned | lower == 'true' }}"

# Show the final weak variable value
- debug:
    var: weak

# result
- block:
    - debug:
        msg: "취약"
    - set_fact:
        result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': True, '조치방안': diag.조치방안}] }}"
  when: weak

- block:
    - debug:
        msg: "양호"
    - set_fact:
        result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': False, '조치방안': diag.조치방안}] }}"
  when: not weak

