# header
- set_fact:
    diag: "PermitRootLogin Check"  ## 점검 내용 이름
    num: 1 ## 점검 번호

# body

# Get PermitRootLogin setting from sshd_config
- name: Get PermitRootLogin setting from sshd_config
  ansible.builtin.shell: grep -E '^[[:space:]]*PermitRootLogin' /etc/ssh/sshd_config
  register: permit_root_login
  ignore_errors: yes

# weak?
- set_fact:
    weak: >
      {% if permit_root_login.rc != 0 %}
        true
      {% elif 'PermitRootLogin no' in permit_root_login.stdout %}
        false
      {% elif 'PermitRootLogin prohibit-password' in permit_root_login.stdout %}
        true
      {% else %}
        true
      {% endif %}
- debug:
    msg: "Weak variable value1: {{ weak }}"

# Remove comments and check the value of weak
- set_fact:
    weak_cleaned: "{{ weak.split('#')[0].strip() }}"

# Debug the cleaned weak value
- debug:
    msg: "Weak cleaned value: '{{ weak_cleaned }}'"

# If weak_cleaned contains 'true' or 'false', set weak to boolean
- set_fact:
    weak: "{{ weak_cleaned | lower == 'true' }}"

# Show the final weak variable value
- debug:
    var: weak

# result
- block:
    - debug:
        msg: "취약"
    - set_fact:
        result: "{{ result + [{'num': num, 'diag': diag, 'weak': True}] }}"
  when: weak

- block:
    - debug:
        msg: "양호"
    - set_fact:
        result: "{{ result + [{'num': num, 'diag': diag, 'weak': False}] }}"
  when: not weak
