# header
- set_fact:
    diag: "PermitRootLogin Check"  ## 점검 내용 이름
    num: 1 ## 점검 번호

# body

# Get PermitRootLogin setting from sshd_config
- name: Get PermitRootLogin setting from sshd_config
  ansible.builtin.shell: grep -E '^[[:space:]]*PermitRootLogin' /etc/ssh/sshd_config
  register: permit_root_login
  ignore_errors: yes

# weak?
- set_fact:
    weak: |
      {% if permit_root_login.rc != 0 %}
        True  # 설정이 없는 경우 취약함
      {% elif 'PermitRootLogin no' in permit_root_login.stdout %}
        False  # 안전함
      {% elif 'PermitRootLogin prohibit-password' in permit_root_login.stdout %}
        True  # prohibit-password
      {% else %}
        True  # 취약함 (기타 경우)
      {% endif %}

# Show the weak variable value
- debug:
    var: weak

# result
- block:
    - debug:
        msg: "취약"
    - set_fact:
        result: "{{ result + [{'num': num, 'diag': diag, 'weak': True}] }}"
  when: weak | bool

- block:
    - debug:
        msg: "양호"
    - set_fact:
        result: "{{ result + [{'num': num, 'diag': diag, 'weak': False}] }}"
  when: (not weak) | bool
