# header
- set_fact:
    diag: "{{ {'항목': '파일 및 디렉터리 소유자 설정', 'id': 7, '조치방안': '소유자가 존재하지 않은 파일은 rm으로 삭제 및 파일이 필요한 경우 chown으로 소유자 변경'} }}"

# body
# Step 1: Find files and directories with no owner or group on the entire system
- name: Find files with no owner or group (system-wide)
  ansible.builtin.shell: sudo find / -nouser -nogroup
  register: system_wide_nouser_nogroup
  ignore_errors: yes

# Step 2: Find files and directories with no owner or group in specific directories
- name: Find files with no owner or group in specific directories
  ansible.builtin.shell: sudo find /etc /tmp /bin /sbin \( -nouser -o -nogroup \) -xdev -exec ls -al {} \; 2>/dev/null
  register: specific_dirs_nouser_nogroup
  ignore_errors: yes

# Step 3: Debug output from system-wide search
- name: Debug system-wide orphaned files and directories
  debug:
    msg: "System-wide orphaned files and directories: {{ system_wide_nouser_nogroup.stdout }}"

# Step 4: Debug output from specific directories search
- name: Debug specific directories orphaned files and directories
  debug:
    msg: "Specific directories orphaned files and directories: {{ specific_dirs_nouser_nogroup.stdout }}"

# Step 5: Determine if there are any orphaned files or directories
- name: Check if there are any orphaned files or directories
  set_fact:
    weak: "{{ (system_wide_nouser_nogroup.stdout != '') or (specific_dirs_nouser_nogroup.stdout != '') }}"

# Step 6: Display the vulnerability status
- name: Display the vulnerability status
  debug:
    msg: >
      Vulnerable? {{ weak | ternary('True', 'False') }}

# Step 7: Provide additional information if vulnerable
- name: Display additional info if system is vulnerable
  debug:
    msg: "Orphaned files or directories exist in the system."
  when: weak

- name: Display message if system is not vulnerable
  debug:
    msg: "No orphaned files or directories found."
  when: not weak

- block:
    - debug:
        msg: "취약"
    - set_fact:
        result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': True, '조치방안': diag.조치방안}] }}"
  when: weak

- block:
    - debug:
        msg: "양호"
    - set_fact:
        result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': False, '조치방안': diag.조치방안}] }}"
  when: not weak
