- set_fact:
    diag: "{{ {'항목': '일반사용자의 sendmail 실행 방지', 'id': 32} }}"  # 항목과 ID 설정

- name: Check for PrivacyOptions in Sendmail configuration
  ansible.builtin.command: "cat /etc/mail/sendmail.cf | grep PrivacyOptions"
  register: sendmail_privacy
  ignore_errors: yes
  failed_when: sendmail_privacy.rc not in [0, 1]

- name: Check if Postfix group exists
  ansible.builtin.command: "getent group postfix"
  register: postfix_group
  ignore_errors: yes
  failed_when: false

- name: Check if Postfix service is active or found
  ansible.builtin.command: "systemctl status postfix"
  register: postfix_status
  ignore_errors: yes
  failed_when: false

- name: Determine if Postfix is not installed
  set_fact:
    postfix_not_installed: "{{ postfix_group.stdout == '' and 'could not be found' in postfix_status.stderr or 'inactive' in postfix_status.stdout }}"

- name: Display Sendmail configuration result
  debug:
    msg: "Sendmail PrivacyOptions check result: {{ sendmail_privacy.stdout }}"

- name: Display Postfix service status
  debug:
    msg: "Postfix service status: {{ postfix_status.stderr if postfix_status.stderr else postfix_status.stdout }}"

- name: Check if Sendmail and Postfix configuration is secure
  debug:
    msg: >
      {{
        'Sendmail is disabled and Postfix is not installed. System is secure.'
        if postfix_not_installed
        else 'Potential issue with Sendmail or Postfix. Requires further investigation.'
      }}

# result 업데이트 블록
- block:
    - debug:
        msg: "취약"
    - set_fact:
        result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': True}] }}"
  when: not postfix_not_installed

- block:
    - debug:
        msg: "양호"
    - set_fact:
        result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': False}] }}"
  when: postfix_not_installed

