---
- name: Check GRANT OPTION from users in MySQL
  hosts: mysql_servers
  become: yes
  vars:
    mysql_root_password: "rockylinux"
  tasks:
    # 헤더
    - set_fact:
        diag: "{{ {'항목': '타 사용자에 권한 부여 옵션 제한', 'id': 3} }}"

    # 결과 초기화
    - set_fact:
        result: []

    - name: Check if GRANT OPTION is assigned to users
      mysql_query:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        query: "SELECT User, Host, Grant_priv FROM mysql.user WHERE User='{{ item.name }}' AND Host='{{ item.host }}';"
      loop:
        - { name: 'test', host: 'localhost' }
      register: grant_option_check

    - name: Show result of GRANT OPTION check
      debug:
        var: grant_option_check

    # 결과 처리
    - block:
        - debug:
            msg: "취약"
        - set_fact:
            result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': True}] }}"
      when: grant_option_check.results[0].query_result | length == 0

    - block:
        - debug:
            msg: "양호"
        - set_fact:
            result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': False}] }}"
      when: grant_option_check.results[0].query_result | length > 0

    - name: 최종 결과 출력
      debug:
        var: result
