---
- name: Check MySQL user configuration
  hosts: mysql_servers
  become: true
  tasks:
    # 헤더
    - set_fact:
        diag: "{{ {'항목': 'root 권한으로 서버 구동 제한', 'id': 5} }}"

    # 결과 초기화
    - set_fact:
        result: []

    - name: Check MySQL user in configuration
      command: grep '^user=' /etc/my.cnf
      register: mysql_user_check

    - name: Show MySQL user configuration
      debug:
        msg: "MySQL user is set to: {{ mysql_user_check.stdout }}"

    # 결과 처리
    - block:
        - debug:
            msg: "취약"
        - set_fact:
            result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': True}] }}"
      when: mysql_user_check.stdout == "user=root"

    - block:
        - debug:
            msg: "양호"
        - set_fact:
            result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': False}] }}"
      when: mysql_user_check.stdout != "user=root"

    - name: 최종 결과 출력
      debug:
        var: result
