---
- name: Check MySQL configuration file permissions
  hosts: mysql_servers
  tasks:
    # 헤더
    - set_fact:
        diag: "{{ {'항목': '환경설정 파일 접근 권한', 'id': 6} }}"

    # 결과 초기화
    - set_fact:
        result: []

    - name: Check permissions for MySQL configuration file
      stat:
        path: /etc/my.cnf
      register: mysql_config_stats

    - name: Show MySQL configuration file permissions
      debug:
        msg: "MySQL configuration file permissions: {{ mysql_config_stats.stat.mode }}; Owner: {{ mysql_config_stats.stat.pw_name }}; Group: {{ mysql_config_stats.stat.gr_name }}"

    # 권한이 0640보다 높으면 취약으로 판정
    - block:
        - debug:
            msg: "취약"
        - set_fact:
            result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': True}] }}"
      when: mysql_config_stats.stat.mode|int < 2560  # 0640 is octal, so its decimal equivalent is 2560

    # 권한이 0640 이상일 경우 양호로 판정
    - block:
        - debug:
            msg: "양호"
        - set_fact:
            result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': False}] }}"
      when: mysql_config_stats.stat.mode|int >= 2560

    # 최종 결과 출력
    - name: 결과 출력
      debug:
        var: result
