---
- hosts: mysql_servers
  remote_user: rockylinux
  become: yes
  tasks:
    # header
    - set_fact:
        diag: "{{ {'항목': '불필요한 MySQL 계정 확인', 'id': 1} }}"
    
    # Initialize result as an empty list
    - set_fact:
        result: []

    - name: Check if unnecessary MySQL accounts exist
      mysql_user:
        name: "{{ item }}"
        state: absent
        login_user: root
        login_password: 'rockylinux'
      loop:
        - 'test'
        - 'guest'
        - 'anonymous'
      register: account_check_results

    - name: Show account existence results
      debug:
        var: item
      loop: "{{ account_check_results.results }}"

    # result
    - block:
        - debug:
            msg: "취약"
        - set_fact:
            result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': True}] }}"
      when: account_check_results.results | selectattr('changed', 'equalto', True) | list | length > 0

    - block:
        - debug:
            msg: "양호"
        - set_fact:
            result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': False}] }}"
      when: account_check_results.results | selectattr('changed', 'equalto', False) | list | length == 3  # 모든 계정이 없던 경우

    - name: 최종 결과 출력
      debug:
        var: result
