# Header
- set_fact:
    diag: "{{ {'항목': '환경설정 파일 접근 권한', 'id': 6, '조치방안': '환경설정 파일 접근 권한 640으로 설정'} }}"

- set_fact:
    result: []

# 6. Set permissions for MySQL configuration file
- name: Set permissions for MySQL configuration file
  file:
    path: /etc/my.cnf
    owner: root
    group: root
    mode: '0640'
  register: permission_result

# Result
- block:
    - debug:
        msg: "취약"
    - set_fact:
        result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': True, '조치방안': diag.조치방안}] }}"
  when: permission_result.changed

- block:
    - debug:
        msg: "양호"
    - set_fact:
        result: "{{ result + [{'id': diag.id, '제목': diag.항목, '취약': False, '조치방안': diag.조치방안}] }}"
  when: not permission_result.changed

# 최종 결과 출력
- name: 결과 출력
  debug:
    var: result
