---
- name: Apache DocumentRoot 취약점 진단
  hosts: intranetweb
  tasks:
    - name: httpd.conf 파일 존재 여부 확인
      stat:
        path: /etc/httpd/conf/httpd.conf
      register: httpd_conf
    - debug:
        msg: "httpd.conf 파일이 존재합니다"
      when: httpd_conf.stat.exists
      
    - name: DocumentRoot 경로 확인 (httpd.conf)
      shell: cat /etc/httpd/conf/httpd.conf | grep DocumentRoot
      register: DocumentRoot_httpd
    - debug:
        msg: >
          {% if DocumentRoot_httpd.stdout | regex_search('DocumentRoot *"/var/www/html"') %}
            "취약"
          {% else %}
            "양호"
          {% endif %}