# header
- set_fact:
    diag: "{{ {'항목': '최신 보안 패치 적용', 'id': 7} }}"

# body

# 1. Run httpd -v to check Apache version
- name: Run httpd -v to check Apache version
  ansible.builtin.command:
    cmd: "httpd -v"
  register: apache_version
  ignore_errors: yes

# 2. Display Apache version details
- name: Display Apache version
  debug:
    msg:
      - "{{ apache_version.stdout.splitlines()[0] }}"
      - "{{ apache_version.stdout.splitlines()[1] }}"

# 3. Set weak variable based on Apache version
# Here, we assume that certain versions (for example, older than 2.4.50) are vulnerable.
- set_fact:
    weak: >
      {% if apache_version.stdout is not defined %}
        true
      {% elif 'Apache/2.4.50' in apache_version.stdout or 'Apache/2.4.51' in apache_version.stdout %}
        false
      {% else %}
        true
      {% endif %}

- debug:
    msg: "Weak variable value: {{ weak }}"

# 4. Final result
- block:
    - debug:
        msg: "취약"
    - set_fact:
        result: "{{ result | default([]) + [{'id': diag.id, '제목': diag.항목, '취약': True}] }}"
  when: weak

- block:
    - debug:
        msg: "양호"
    - set_fact:
        result: "{{ result | default([]) + [{'id': diag.id, '제목': diag.항목, '취약': False}] }}"
  when: not weak
