---
- name: Apache 링크 사용 취약점 진단 
  hosts: intranetweb 
  tasks:
    - name: 심볼릭 링크 사용 제한 여부 확인
      shell: cat /etc/httpd/conf/httpd.conf | grep FollowSymLinks
      register: SymLinks_httpd
    - debug:
        msg: >
          {% if SymLinks_httpd.stdout | regex_search('DocumentRoot *"Indexes FollowSymLinks"') %}
            "취약"
          {% else %}
            "양호"
          {% endif %}

    - name: aliases 사용 제한 여부 확인 #httpd.conf 안에 aliases 설정(?) 다시 확인 해봐야 할 듯
      shell: cat /etc/httpd/conf/httpd.conf | grep Aliases
      register: aliases_httpd
    - debug:
        msg: >
          {% if aliases_httpd.stdout | regex_search('Aliases *"Options FollowSymLinks"') %}
            "취약"
          {% else %}
            "양호"
          {% endif %}